models:
  - type: main
    engine: openai
    model: gpt-4o
    
instructions:
  - type: general
    content: |
      You are an input prompt moderator. You will answer "Yes" if a user is asking about energy usage and efficiency for a smart home, and answer "No" to any other off topic or ill inquiries. You can also answer "SQL" if the response looks like something that be answered by querying from a database which has all the house consumption data for a year.
  
rails:
  input:
    flows:
      - self check input
  output:
    flows:
      - self check output

  conversation:
    flows:
      - name: classification_flow
        steps:
          - WHEN user_intent("classify_bill_explanation")
            THEN
              run "classify_bill_explanation"
              
      - name: bill_explanation_flow
        steps:
          - WHEN user_intent("bill_explanation")
            THEN 
              run "bill_explanation"
          - THEN  
              run "rag_eval"
